// Games We Play - static data for homepage
export const games = [
  {
    id: '4pics1word',
    name: '4 Pics 1 Word',
    logo: '/games/4pics1word.jpg',
    banner: '/games/4pics1word-banner.jpg',
    description: 'Word puzzles, quick thinking, and group laughs. Our cabal cracks the code!',
    strengths: ['Wordplay', 'Teamwork', 'Puzzle-solving'],
    requires_id: false,
    external_link: 'discord.gg/vsw8nm7qtk',
    type: 'room',
    platform: 'mobile',
  },
  {
    id: 'amongus',
    name: 'Among Us',
    logo: '/games/amongus-logo.jpg',
    banner: '/games/amongus-banner.jpg',
    description: 'Deception, deduction, and hilarious betrayals. Trust no one!',
    strengths: ['Deception', 'Deduction', 'Social play'],
    requires_id: false,
    type: 'room',
    platform: 'mobile',
  },
  {
    id: 'scrabble',
    name: 'Scrabble',
    logo: '/games/scrabble.jpg',
    banner: '/games/scrabble-banner.jpg',
    description: 'Classic word battles. Where vocabulary meets victory.',
    strengths: ['Vocabulary', 'Strategy', 'Chill vibes'],
    requires_id: true,
    //external_link: 'https://scrabble.com/',
    type: 'pvp',
    platform: 'web',
  },
  {
    id: 'poker',
    name: 'Poker',
    logo: '/games/poker.jpg',
    banner: '/games/poker-banner.jpg',
    description: 'Bluff, bet, and win big. Our cabal’s got the best poker faces.',
    strengths: ['Bluffing', 'Math', 'Risk-taking'],
    requires_id: false,
    //external_link: 'https://www.pokerstars.net/',
    type: 'room',
    platform: 'web',
  },
  {
    id: 'codm',
    name: 'Call of Duty Mobile (CODM)',
    logo: '/games/codm.png',
    banner: '/games/codm-banner.jpg',
    description: 'Mobile FPS action. Fast reflexes, sharp aim, and squad tactics.',
    strengths: ['FPS', 'Tactics', 'Mobile mastery'],
    requires_id: false,
    external_link: null,
    type: 'room',
    platform: 'mobile',
  },
  {
    id: 'chess',
    name: 'Chess',
    logo: '/games/chess.jpg',
    banner: '/games/chess-banner.jpg',
    description: 'Strategy, patience, and mind games. Our thinkers rule the board.',
    strengths: ['Strategy', 'Patience', 'Classic play'],
    requires_id: false,
    external_link: null,
    type: 'room',
    platform: 'web',
  },
  {
    id: 'racing',
    name: 'Racing',
    logo: '/games/racing.png',
    banner: '/games/racing-banner.jpg',
    description: 'Speed, skill, and photo finishes. Who’s the fastest in the cabal?',
    strengths: ['Speed', 'Reflexes', 'Competition'],
    requires_id: false,
    external_link: null,
    type: 'room',
    platform: 'mobile',
  },
  {
    id: '8ball',
    name: '8 Ball Pool',
    logo: '/games/8ball.png',
    banner: '/games/8ball-banner.jpg',
    description: 'Classic pool game. Precision, angles, and trick shots!',
    strengths: ['Precision', 'Angles', 'Strategy'],
    requires_id: true,
    external_link: null,
    type: 'pvp',
    platform: 'web',
  },
  {
    id: 'efootball',
    name: 'eFootball',
    logo: '/games/efootball.png',
    banner: '/games/efootball-banner.jpg',
    description: 'Football simulation, skill moves, and online matches.',
    strengths: ['Football', 'Skill', 'Competition'],
    requires_id: true,
    external_link: null,
    type: 'pvp',
    platform: 'mobile',
  },
  {
    id: 'minimilitia',
    name: 'Mini Militia',
    logo: '/games/minimilitia.png',
    banner: '/games/minimilitia-banner.jpg',
    description: 'Multiplayer combat, jetpacks, and mayhem!',
    strengths: ['Combat', 'Multiplayer', 'Fun'],
    requires_id: false,
    external_link: null,
    type: 'room',
    platform: 'mobile',
  },
  {
    id: 'geoguessr',
    name: 'GeoGuessr',
    logo: '/games/geoguessr.png',
    banner: '/games/geoguessr-banner.jpg',
    description: 'Explore the world, guess locations, and test your geography skills.',
    strengths: ['Geography', 'Exploration', 'Puzzle'],
    requires_id: false,
    external_link: null,
    type: 'room',
    platform: 'web',
  },
  {
    id: 'discordgames',
    name: 'Discord Games',
    logo: '/games/discordgames.png',
    banner: '/games/discordgames-banner.jpg',
    description: 'Play games directly in Discord with friends.',
    strengths: ['Social', 'Party', 'Casual'],
    requires_id: false,
    external_link: 'discord.gg/vsw8nm7qtk',
    type: 'room',
    platform: 'discord',
  },
  {
    id: 'freefire',
    name: 'Free Fire',
    logo: '/games/freefire.png',
    banner: '/games/freefire-banner.jpg',
    description: 'Battle royale on mobile. Fast drops, wild plays, and epic wins.',
    strengths: ['Battle Royale', 'Mobile', 'Clutch'],
    requires_id: true,
    external_link: null,
    type: 'pvp',
    platform: 'mobile',
  },
  {
    id: 'pubg',
    name: 'PUBG',
    logo: '/games/pubg.png',
    banner: '/games/pubg-banner.jpg',
    description: 'Tense firefights, big maps, and chicken dinners. Squad up!',
    strengths: ['Tactics', 'Survival', 'Squad play'],
    requires_id: true,
    external_link: null,
    type: 'pvp',
    platform: 'mobile',
  },
  {
    id: 'bloodstrike',
    name: 'Blood Strike',
    logo: '/games/bloodstrike.png',
    banner: '/games/bloodstrike-banner.jpg',
    description: 'Fast-paced shooter action. Our cabal brings the heat!',
    strengths: ['FPS', 'Aggression', 'Teamwork'],
    requires_id: true,
    external_link: null,
    type: 'pvp',
    platform: 'mobile',
  },
];
